[book]
authors = ["Lucas Javaudin"]
language = "en"
src = "src"
title = "MobiSurvStd"

[output.html]
default-theme = "rust"
preferred-dark-theme = "navy"
smart-punctuation = true
mathjax-support = false
git-repository-url = "https://github.com/LucasJavaudin/MobiSurvStd"
git-repository-icon = "fa-github"
# site-url = "/example-book/"
additional-css = ["theme/pagetoc.css"]
additional-js = ["theme/pagetoc.js"]
